apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rubber-fowl-python 
  janus-idp.io/tekton: rubber-fowl-python
  backstage.io/kubernetes-id: rubber-fowl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rubber-fowl-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  